dataset_type: fan
fan_section: s1
use_cuda: True
device: cuda
use_fft: False
use_hilbert_envelope: True
use_domain_weight: True
data_length: 2560
use_angular_resample: True
unified_Os: 350
# training
batch_size: 64
num_classes: 2
steps: 100
checkpoint_freq: 1
lr: 0.0001
w_ca: 1
w_rc: 1
w_rr: 0.1
use_learning_rate_sheduler: True
cos: False
schedule: [50, 100, 150]
gamma: 0.5
best_auc: -1
grad_clip: 5.0
eps: 1e-8