dataset_debug: False
dataset_type: fan # bearing or fan
fan_section: 00 # sec00, sec01, sec02
use_cuda: True
device: cuda
use_hilbert_envelope: True
use_domain_weight: False
domain_weight_scale: 1.5
use_fft: False # input data form (raw original signal or frequency spectrum)
data_length: 2560
unified_Os: 350 # 转轴每转一圈采样点的数目
use_angular_resample: True
# basic model parameters
batch_size: 64 # 32 for fan, 64 for bearing
num_classes: 2 # 2 for fan, 3 for bearing

# basic training parameters
steps: 100 # the number of iteration, 200 for bearing and 100 for fan (because the fan dataset is small)
checkpoint_freq: 1

lr: 0.0001  # 学习率
margin: 1

lbda_cr: 100
lbda_tp: 0.1










